### PR TITLE
Fix-up add key modal.

### LINKED ISSUE #12: Newly added key is not displayed
In the br-keys component, you may go to the action menu and choose 'Add Key'.  Fill in the form with a public PEM.  Hit 'Save'.  The ID/URL is displayed for the new key, then click 'Done'.  The new key is not displayed by br-keys until the component is reloaded or refreshed.

### PR DESCRIPTION
**Pull request by mattcollier**
Fixes #12.

Also moves brKeyService operations out of the add-key-modal-component.  However, I don't know if any of the changes here adversely affect what happens when `$routeParams.service` is being utilized.  Do we have a way of testing that code path?

### CODE REVIEW

**Comment by dlongley** [comment]
> However, I don't know if any of the changes here adversely affect what happens when $routeParams.service is being utilized. Do we have a way of testing that code path?

I think we should just completely remove that code path. That's from an old Web Keys registration spec that we would likely do differently now anyway.

**Comment by mattcollier** [comment]
@dlongley ready for another pass.

**Comment by dlongley** [comment]
@mattcollier, LGTM. However, we're going to have to do a semver major bump on this and fix up other places that were relying on the modal to do the brKeyService stuff.

**Comment by mattcollier** [comment]
@dlongley I had searched previously and found that the add-key modal is not used directly anywhere.  Do you have reason to believe otherwise?

**Comment by mattcollier** [comment]
@dlongley Which means to me that a semver major is not required.

**Comment by dlongley** [comment]
I don't think that should be our bar for determining semver major in general (rather, it's just a question of breaking changes), but in this particular case, in the interest of expediency, I'm fine with non-semver major release.

**Pull request merged**
